# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Deplace to project
      run: cd Sources
    - name: Restore dependencies 
      run: |
        cd Sources
        dotnet restore OpenLibraryWS_Wrapper.sln
    - name: Build
      run: |
        cd Sources
        dotnet restore OpenLibraryWS_Wrapper.sln 
        dotnet build OpenLibraryWS_Wrapper.sln -c Release --no-restore
    - run:  |
        cd Sources
        dotnet restore OpenLibraryWS_Wrapper.sln 
        dotnet build OpenLibraryWS_Wrapper.sln -c Release --no-restore
        echo "${{ env.DOTNET_INSTALL_DIR }}" 
        dotnet publish OpenLibraryWS_Wrapper.sln -c Release --no-restore -o ${{ env.DOTNET_INSTALL_DIR }}/build/release
  
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Deplace to project
      run: cd Sources
    - name: Restore dependencies 
      run: |
        cd Sources
        dotnet restore OpenLibraryWS_Wrapper.sln
    - name: Test
      run: |
        cd Sources
        dotnet restore OpenLibraryWS_Wrapper.sln
        dotnet test OpenLibraryWS_Wrapper.sln --no-restore
    needs: build
