# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Deplace to project
      run: cd Sources
    - name: Restore dependencies 
      run: |
        pwd
        echo ----------------
        ls
        echo ------------------
        dotnet restore OpenLibraryWS_Wrapper.sln
    - name: Build
      run: dotnet build OpenLibraryWS_Wrapper.sln -c Release --no-restore
    - name: Publish
      run:  dotnet publish OpenLibraryWS_Wrapper.sln -c Release --no-restore -o $CI_PROJECT_DIR/build/release
    - name: Test
      run: dotnet test OpenLibraryWS_Wrapper.sln --no-restore
  
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Deplace to project
      run: cd Sources
    - name: Restore dependencies 
      run: dotnet restore OpenLibraryWS_Wrapper.sln
    - name: Test
      run: dotnet test OpenLibraryWS_Wrapper.sln --no-restore
    needs: build
